export enum TipoDocumentoEnum {
  CEDULA_CIUDADANIA = "CC",
  CEDULA_EXTRANJERA = "CE",
  TARJETA_IDENTIDAD = "TI",
  PASAPORTE = "PA",
  REGISTO_CIVIL = "RC",
  CARNE_DIMPLOMATICO = "CD",
  SALVOCONDUCTO = "SC",
  CERTIFICADO_NACIDO_VIVO = "CN",
  ADULTO_SIN_IDENTIFICAR = "AS",
  MENOR_SIN_IDENTIFICAR = "MS",
  PERMISO_PROTECCION_TEMPORAL = "PT",
  ERROR = "ERROR"
}
