
export enum TipoDiscapacidadEnum{

    PERMANENTE = "PERMANENTE",
    TEMPORAL = "TEMPORAL",
    AUDITIVA = "AUDITIVA",
    COGNITIVA = "COGNITIVA",
    FISICA = "FISICA",
    MENTAL = "MENTAL",
    VISUAL = "VISUAL",
    MULTIPLE = "MULTIPLE",

}