export enum IdentidadGeneroEnum {
  MASCULINO = 'MASCULINO',
  FEMENINO = 'FEMENINO',
  TRAVESTI = 'TRAVESTI',
  TRANSEXUAL = 'TRANSEXUAL',
  TRANSGENERO = 'TRANSGENERO',
  NINGUNA ="NINGUNA",
  NO_BINARIO = "NO BINARIO",
}
