export enum TipoDocumentoEnum {
  CC = 'CEDULA_CIUDADANIA',
  CE = 'CEDULA_EXTRANJERA',
  TI = 'TARJETA_IDENTIDAD',
  PA = 'PASAPORTE',
  RC = 'REGISTO_CIVIL',
  CD = 'CARNE_DIMPLOMATICO',
  SC = 'SALVOCONDUCTO',
  CN = 'CERTIFICADO_NACIDO_VIVO',
  AS = 'ADULTO_SIN_IDENTIFICAR',
  MS = 'MENOR_SIN_IDENTIFICAR',
  PT = 'PERMISO_PROTECCION_TEMPORAL',
}
